import { answeredQuestion, unansweredQuestion } from "./type";

const mockCreatedAt = new Date(2024, 0, 1);
const mockAnsweredAt = new Date(2024, 1, 1);

//全ての未回答の質問
export const allUnansweredQuestionMock: unansweredQuestion[] = [
  {
    id: "aaaaaaaaaaaaaa",
    question: "バナナはおやつですか",
    keyword: "バナナ",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
  {
    id: "bbbbbbbbbbbbbb",
    question: "りんごはおやつですか",
    keyword: "りんご",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
  {
    id: "cccccccccccccc",
    question: "みかんはおやつですか",
    keyword: "みかん",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
  {
    id: "dddddddddddddd",
    question: "バナナはおやつですか",
    keyword: "いちご",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
  {
    id: "eeeeeeeeeeeeeee",
    question: "スイカはおやつですか",
    keyword: "スイカ",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
  {
    id: "ffffffffffffffff",
    question: "しいたけはおやつですか",
    keyword: "しいたけ",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
  {
    id: "ggggggggggggggggggg",
    question: "ももはおやつですか",
    keyword: "もも",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
  {
    id: "hhhhhhhhhhhhhhhhh",
    question: "たにしはおやつですか",
    keyword: "たにし",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
  {
    id: "iiiiiiiiiiiiiiiii",
    question: "じゃがいもはおやつですか",
    keyword: "じゃがいも",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
  {
    id: "jjjjjjjjjjjjjjjjj",
    question: "かぼちゃはおやつですか",
    keyword: "かぼちゃ",
    createdAt: mockCreatedAt,
    answer: null,
    answeredAt: null,
  },
];

// 全ての回答済みの質問
export const allAnsweredQuestionMock: answeredQuestion[] = [
  {
    id: "kkkkkkkkkkkkk",
    question: "バナナはおかずですか",
    answer: "おかずです",
    keyword: "バナナ",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
  {
    id: "llllllllllllll",
    question: "りんごはおかずですか",
    answer: "おかずです",
    keyword: "りんご",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
  {
    id: "mmmmmmmmmmmmmm",
    question: "みかんはおかずですか",
    answer: "おかずです",
    keyword: "みかん",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
  {
    id: "nnnnnnnnnnnnnnn",
    question: "バナナはおかずですか",
    answer: "おかずです",
    keyword: "いちご",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
  {
    id: "ooooooooooooooooo",
    question: "スイカはおかずですか",
    answer: "おかずです",
    keyword: "スイカ",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
  {
    id: "ppppppppppppppppppp",
    question: "しいたけはおかずですか",
    answer: "おかずです",
    keyword: "しいたけ",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
  {
    id: "qqqqqqqqqqqqqqq",
    question: "ももはおかずですか",
    answer: "おかずです",
    keyword: "もも",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
  {
    id: "rrrrrrrrrrrrrrrrrrrr",
    question: "たにしはおかずですか",
    answer: "おかずです",
    keyword: "たにし",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
  {
    id: "sssssssssssssssssssss",
    question: "じゃがいもはおかずですか",
    answer: "おかずです",
    keyword: "じゃがいも",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
  {
    id: "tttttttttttttttttttt",
    question: "かぼちゃはおかずですか",
    answer: "おかずです",
    keyword: "かぼちゃ",
    createdAt: mockCreatedAt,
    answeredAt: mockAnsweredAt,
  },
];